# Generated by Django 3.2.9 on 2021-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211211_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False, verbose_name='Applicant Users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subadmin',
            field=models.BooleanField(default=False, verbose_name='Sub Admin User'),
        ),
    ]
